secret: 1234567890qwertyuiopasdfghjklzxcvbnm
database:
  host: localhost
  port: 5432
  username: admin
  password: SECRET
  name: mydatabase
logging:
  level: INFO
  file: /var/log/myapp.log
features:
  enable_feature_x: true
  enable_feature_y: false 